# Generated by Django 4.2.7 on 2023-11-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.SlugField(max_length=250)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_fabrication', models.DateField()),
                ('couleur', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Dis', 'Disponible'), ('InDis', 'IndDisponible')], default='Dis', max_length=5)),
            ],
            options={
                'ordering': ['annee_fabrication', 'marque', 'modele'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('mise_ajour_date', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateField()),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombres_jours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_voiture.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_voiture.voiture')),
            ],
        ),
    ]
