# Generated by Django 4.2.7 on 2023-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_voiture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
